GET http://localhost:8000/products/ HTTP/1.1


###
GET http://localhost:8000/products/10 HTTP/1.1


###
DELETE  http://localhost:8000/products/10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzI3Mjk3LCJpYXQiOjE3Mzc3MjY5OTcsImp0aSI6IjVhZjFmZjE5NWZhNzQ0NTA4MTVjNjJlOTRlNTIwOWUzIiwidXNlcl9pZCI6MX0.FORogXEFebR11gXpTO_vZT0FKpapywxPAb0bY1ion_o


###
PUT http://localhost:8000/products/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzI3Mjk3LCJpYXQiOjE3Mzc3MjY5OTcsImp0aSI6IjVhZjFmZjE5NWZhNzQ0NTA4MTVjNjJlOTRlNTIwOWUzIiwidXNlcl9pZCI6MX0.FORogXEFebR11gXpTO_vZT0FKpapywxPAb0bY1ion_o

{
    "name": "Phone",
    "description": "wine",
    "stock": 2,
    "price": "100.99"
  }


###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzI2MDYwLCJpYXQiOjE3Mzc3MjU3NjAsImp0aSI6ImI5ZTYxMDczZGYzZTQwODNiN2NlMWIzMTAwYzdjOTUyIiwidXNlcl9pZCI6MX0.k3e1pXpIETkKVX9yuu-SuVpn3mnpGHBaj6YNC9afxkg

{
    "name": "Phone",
    "description": "wine",
    "stock": 2,
    "price": "100.99"
  }


###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "saga",
    "password": "test"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzgxMjczNiwiaWF0IjoxNzM3NzI2MzM2LCJqdGkiOiI3NzI5NmIyNmNiYmI0YWE2ODM3ODEyMWIyMGRjM2MyNCIsInVzZXJfaWQiOjF9.vX_AhQCtVKV6wR-SBxf6lYCGaQTuQAnhpXj9errzWHk"
}

###
GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzI2MDYwLCJpYXQiOjE3Mzc3MjU3NjAsImp0aSI6ImI5ZTYxMDczZGYzZTQwODNiN2NlMWIzMTAwYzdjOTUyIiwidXNlcl9pZCI6MX0.k3e1pXpIETkKVX9yuu-SuVpn3mnpGHBaj6YNC9afxkg


###
GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzM4NTE5LCJpYXQiOjE3Mzc3MzgyMTksImp0aSI6IjMzNTQ4ZTdjYTg1NDQ0YmQ4OGM1MmEzODZhYmY5NDA1IiwidXNlcl9pZCI6MX0.4X5O36dzjekeVeSL6_Ff0aSQfKqYVlPdzRLC-eUr22c

###
GET http://localhost:8000/orders/111da90e-6c53-4842-86db-ad205201c02e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzM4NjY0LCJpYXQiOjE3Mzc3MzgzNjQsImp0aSI6IjZkZjMxYTk5ZDM1ODQ2NjU4NzYxOWNkYjNlOGVkY2JiIiwidXNlcl9pZCI6Mn0.hDoEavJnMkwwZExIoaZjxsif9IZ5AuVcwU0wXKNE9Q4