GET http://localhost:8000/products/ HTTP/1.1


###
GET http://localhost:8000/products/10 HTTP/1.1


###
DELETE  http://localhost:8000/products/10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzI3Mjk3LCJpYXQiOjE3Mzc3MjY5OTcsImp0aSI6IjVhZjFmZjE5NWZhNzQ0NTA4MTVjNjJlOTRlNTIwOWUzIiwidXNlcl9pZCI6MX0.FORogXEFebR11gXpTO_vZT0FKpapywxPAb0bY1ion_o


###
PUT http://localhost:8000/products/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzI3Mjk3LCJpYXQiOjE3Mzc3MjY5OTcsImp0aSI6IjVhZjFmZjE5NWZhNzQ0NTA4MTVjNjJlOTRlNTIwOWUzIiwidXNlcl9pZCI6MX0.FORogXEFebR11gXpTO_vZT0FKpapywxPAb0bY1ion_o

{
    "name": "Phone",
    "description": "wine",
    "stock": 2,
    "price": "100.99"
  }


###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzI2MDYwLCJpYXQiOjE3Mzc3MjU3NjAsImp0aSI6ImI5ZTYxMDczZGYzZTQwODNiN2NlMWIzMTAwYzdjOTUyIiwidXNlcl9pZCI6MX0.k3e1pXpIETkKVX9yuu-SuVpn3mnpGHBaj6YNC9afxkg

{
    "name": "Phone",
    "description": "wine",
    "stock": 2,
    "price": "100.99"
  }


###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "saga",
    "password": "test"
}

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczNzgxMjczNiwiaWF0IjoxNzM3NzI2MzM2LCJqdGkiOiI3NzI5NmIyNmNiYmI0YWE2ODM3ODEyMWIyMGRjM2MyNCIsInVzZXJfaWQiOjF9.vX_AhQCtVKV6wR-SBxf6lYCGaQTuQAnhpXj9errzWHk"
}


###
GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3Nzk5MDA5LCJpYXQiOjE3Mzc3OTg3MDksImp0aSI6IjgxYWY3M2NlNGUyODQzNWZhOWYyMmE0ZDE5NTFiNmIzIiwidXNlcl9pZCI6Mn0.3Qx_OCGn7nFROMkBsqdPLrqDoUaUjBtEzSDSYCOaE74
###
GET http://localhost:8000/orders/111da90e-6c53-4842-86db-ad205201c02e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3Nzk0MjQ5LCJpYXQiOjE3Mzc3OTM5NDksImp0aSI6ImZlYjI4NjNiNWZmOTQyNmNiODc1ODIyNWFiN2RiYzI1IiwidXNlcl9pZCI6Mn0.sk_I_-DDRS0bI3WB9SPZ3Bgo5bWBWnN0N9_lObkjlu8

###
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3NzkzMDM0LCJpYXQiOjE3Mzc3OTI3MzQsImp0aSI6ImQxZmVlNjJlYWQ2NTQ1MjhhNTI1NGRjZDM2NTRjZmY0IiwidXNlcl9pZCI6Mn0.3_KgO1HfoZ1RXdvNGGTzybfqf2djXWjVC1tCXEiDQww

{
  "status": "Pending",
  "items": [
    {
      "product": 7,
      "quantity": 1
    },
    {
      "product": 8,
      "quantity": 2
    }
  ]
}

###
PUT http://localhost:8000/orders/3fdd2e03-3af9-4d51-9101-f43eb6283e42/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3Nzk0MjQ5LCJpYXQiOjE3Mzc3OTM5NDksImp0aSI6ImZlYjI4NjNiNWZmOTQyNmNiODc1ODIyNWFiN2RiYzI1IiwidXNlcl9pZCI6Mn0.sk_I_-DDRS0bI3WB9SPZ3Bgo5bWBWnN0N9_lObkjlu8

{
  "status": "Pending",
  "items": [
    {
      "product": 7,
      "quantity": 9
    },
    {
      "product": 8,
      "quantity": 2
    }
  ]
}

###
DELETE  http://localhost:8000/orders/3fdd2e03-3af9-4d51-9101-f43eb6283e42/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3Nzk0MjQ5LCJpYXQiOjE3Mzc3OTM5NDksImp0aSI6ImZlYjI4NjNiNWZmOTQyNmNiODc1ODIyNWFiN2RiYzI1IiwidXNlcl9pZCI6Mn0.sk_I_-DDRS0bI3WB9SPZ3Bgo5bWBWnN0N9_lObkjlu8
